version: '3'
services:

    # Application container
    php:
        build: .
        restart: unless-stopped
        volumes:
            - ./src:/server/http
        ports:
            - "8080:80"
            #- "443:443"
        depends_on:
            # - postgres
            # - redis
            - mysql
        environment:
            DEBUG: 'true'
    
    mysql:
        image: mysql:5.7
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: hellofresh
            MYSQL_USER: hellofresh
            MYSQL_PASSWORD: hellofresh 
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: hellofresh
            PMA_PASSWORD: hellofresh
        depends_on:
            - mysql
    volumes:
        db_data:
    # postgres:
    #     image: onjin/alpine-postgres:9.5
    #     restart: unless-stopped
    #     ports:
    #         - "5432:5432"
    #     environment:
    #         LC_ALL: C.UTF-8
    #         POSTGRES_USER: hellofresh
    #         POSTGRES_PASSWORD: hellofresh
    #         POSTGRES_DB: hellofresh

    # redis:
    #     image: sickp/alpine-redis:3.2.2
    #     restart: unless-stopped
    #     ports:
    #         - "6379:6379"

